### ISSUE TITLE
CRAB not honoring maxjobruntime on resubmit

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5389]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2568/3/2/1/1.html

relevant text pasted below:
```

Here the log of the resubmission:
DEBUG 2017-02-13 08:53:49,603:   Myproxy is valid: 2246289
DEBUG 2017-02-13 08:53:49,603:   Command use: resubmit
DEBUG 2017-02-13 08:53:49,603:   Options use: ['--maxjobruntime=2000',
'--maxmemory=3000',
'./crab_projects_V25_1/crab_VHBB_HEPPY_V25_SingleMuon__Run2016H-PromptReco-v2/']
DEBUG 2017-02-13 08:53:50,136:   CRABClient version: 3.3.1611
DEBUG 2017-02-13 08:53:50,136:   Instance is prod
DEBUG 2017-02-13 08:53:50,136:   Server base url is cmsweb.cern.ch
DEBUG 2017-02-13 08:53:50,136:   Command url /crabserver/prod/workflow
DEBUG 2017-02-13 08:53:50,136:   Requesting resubmission of failed
jobs in task 170130_120108:arizzi_crab_VHBB_HEPPY_V25_SingleMuon__Run2016H-PromptReco-v2
INFO 2017-02-13 08:53:50,136:    Sending resubmit request to the server.
DEBUG 2017-02-13 08:53:50,137:   Submitting {'maxjobruntime': 2000,
'force': 0, 'publication': 0, 'workflow':
u'170130_120108:arizzi_crab_VHBB_HEPPY_V25_SingleMuon__Run2016H-PromptReco-v2',
'maxmemory': 3000, 'subresource': 'resubmit'}
DEBUG 2017-02-13 08:53:50,137:   Encoded resubmit request:
maxjobruntime=2000&force=0&publication=0&workflow=170130_120108%3Aarizzi_crab_VHBB_HEPPY_V25_SingleMuon__Run2016H-PromptReco-v2&ma
xmemory=3000&subresource=resubmit
DEBUG 2017-02-13 08:53:53,849:   Result: {u'result': [{u'result':
u'ok'}], u'desc': {u'columns': [u'tm_site_blacklist',
u'tm_site_whitelist', u'tm_maxjobruntime', u'tm_maxmemory', u'tm_numc
ores', u'tm_priority']}}
INFO 2017-02-13 08:53:53,849:    Resubmit request sent to the server.
INFO 2017-02-13 08:53:53,849:    Please use 'crab status' to check how
the resubmission process proceeds.
Notice it may take a couple of minutes for the resubmission to get
fully processed.
INFO 2017-02-13 08:53:53,851:    Log file is
/scratch/arizzi/crab_sub/crab_projects_V25_1/crab_VHBB_HEPPY_V25_SingleMuon__Run2016H-PromptReco-v2/crab.log

here the log of the job
https://cmsweb.cern.ch/scheddmon/0121/cms823/170130_120108:arizzi_crab_VHBB_HEPPY_V25_SingleMuon__Run2016H-PromptReco-v2/job_out.771.4.txt

where I read
[...]
== JOB AD: MaxWallTimeMins = 1250
[...]

was this fixed in the same bugfix of the blacklist or is it a different problem?

ciao
andrea

```

**Comment by mmascher** [comment]
Already fixed in https://github.com/dmwm/CRABServer/issues/5363 but the task was an old one.

**Comment by belforte** [comment]
Seems not fixed yet. At least not in all cases. Or maybe we changed something else which broke it !

I have jobs which I resubmit with e.g.
`cmslpc34:nobackup$ crab resubmit -d crab_JetHTRun2017F_17Nov2017_v1-v1/ --maxjobruntime=60`
where the client log shows indeed
```
DEBUG 2019-03-21 14:01:30,995: 	 Requesting resubmission of failed jobs in task 190320_212049:belforte_crab_JetHTRun2017F_17Nov2017_v1-v1
INFO 2019-03-21 14:01:30,995: 	 Sending resubmit request to the server.
DEBUG 2019-03-21 14:01:30,995: 	 Submitting {'maxjobruntime': 60, 'publication': 0, 'jobids': ['2125', '2124', '580', '2127', '2126', '1184'], 'subresource': 'resubmit2', 'workflow': u'190320_212049:belforte_crab_JetHTRun2017F_17Nov2017_v1-v1'} 
DEBUG 2019-03-21 14:01:30,995: 	 Encoded resubmit request: maxjobruntime=60&publication=0&subresource=resubmit2&workflow=190320_212049%3Abelforte_crab_JetHTRun2017F_17Nov2017_v1-v1&jobids=2125&jobids=2124&jobids=580&jobids=2127&jobids=2126&jobids=1184
DEBUG 2019-03-21 14:01:31,802: 	 Result: {u'result': [{u'result': u'ok'}], u'desc': {u'columns': [u'tm_site_blacklist', u'tm_site_whitelist', u'tm_maxjobruntime', u'tm_maxmemory', u'tm_numcores', u'tm_priority']}}
INFO 2019-03-21 14:01:31,802: 	 Resubmit request sent to the server.
```
and when looking at TW log, consistently:
```
belforte@crab-prod-tw01/belforte> tail -20 190320_212049:belforte_crab_JetHTRun2017F_17Nov2017_v1-v1.log|tr ',' '\n'|grep time
 u'tm_maxjobruntime': 30
 u'tm_start_time': u'1553116849'
 u'tm_arguments': {u'maxjobruntime': 60
 u'resubmit_maxjobruntime': 60
belforte@crab-prod-tw01/belforte> 
```
But when looking in the schedd's submit JDL:
```
belforte@vocms0198/SPOOL_DIR> cat Job.2127.submit|grep +MaxWallTime
+MaxWallTimeMinsRun = 30
+MaxWallTimeMins = 30
belforte@vocms0198/SPOOL_DIR> 
```

maybe some change done for the automatic time tuning forces MaxWallTimeMins to be what is recorded in the Task DB.

**Comment by belforte** [comment]
info is passed to schedd OK `adjust_out.txt` has
```
 [
        MaxWallTimeMins_RAW = 60; 
        CRAB_ASOTimeout = 86400; 
        MaxHosts = 1; 
        RequestMemory_RAW = 2000; 
        CRAB_TFileOutputFiles = 
           {

```

**Comment by belforte** [comment]
But the PreJobs does something funny:
```
belforte@vocms0198/prejob_logs> cat prejob.580.5.txt|grep -i wall
        MaxWallTimeMins_RAW = 60; 
        MaxWallTimeMinsTail = 225; 
        MaxWallTimeMinsRun = 30; 
        MaxWallTimeMinsProbe = 60; 
        MaxWallTimeMins = 75; 
        RemoteWallClockTime = 5.480900000000000E+04; 
belforte@vocms0198/prejob_logs> 

```

**Comment by belforte** [comment]
Checked PreJob log and code and found no clue at why the Job.X.submit has not the new attribute.

**Comment by belforte** [comment]
need ad hoc debugging on a simpler task

**Comment by belforte** [comment]
Maybe
MaxWallTimeMins
vs
MaxWallTimeMinsRun
?

**Comment by belforte** [comment]
Indeed. in https://github.com/dmwm/CRABServer/commit/a0550be0663fb171b2a7fba810152f140ede7503
I missed to update DagmanResubmitter as well

**Comment by belforte** [comment]
since it is a new thing, I am closing this and will have an ad hoc issue instead
