### ISSUE TITLE
fix ASO data sending to MONIT for Grafana

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6274]
I have "saved" in the repository
https://github.com/dmwm/CRABServer/blob/master/src/script/Monitor/aso_metrics_ora.py
which was being run on vocm0105 to feed Grafana dashboard
https://monit-grafana.cern.ch/d/JQG5D3mZz/crab-asometrics?orgId=11&refresh=30m
via this crontab:
```
*/5 * * * * source /data/srv/asyncstageout/current/sw.*/*/cms/asyncstageout/*/etc/profile.d/init.sh ;  python /data/srv/asyncstageout/current/apps/asyncstageout/bin/aso_metrics_ora.py > /dev/null
```

The scrip takes input from the DB, so there is no reason to run it on vocms0105 and we should be able to run it in the TW along (or as part of) https://github.com/dmwm/CRABServer/blob/master/src/script/Monitor/GenerateMONIT.py

OTOH it needs some fixing since

- [ ] it stopped sending data on Oct 27 [*]
- [ ] top left plot has a high, moving baseline which makes no sense
- [ ] publication plots are empty since "ever"
- [ ] script name could also be improved

[*]
![Screenshot from 2020-11-26 18-14-00](https://user-images.githubusercontent.com/1837785/100378328-840fc700-2fd8-11eb-88b3-94c90f49205a.png)

**Comment by belforte** [comment]
@sharmaprajesh @ddaina does one of you feel like taking care of this ? I think it is mostly an exercise in understanding how to send data to MONIT. I can certainly help with the calls to crabserver DB, but I believe they should work as they are. While it is possible that when running on a different machine we need different authorization for sending data to MONIT or anyhow find a way to label data which is not the host name.
I think this can be done in a week.
Some more info for reading transfersdb is in https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#URL_s_to_access_transferdb , besides that one has to read the code.

Of course we are open to doing things in a different way etc., the important thing is to have a sense that transfers "works". And while for Publication we can use logstash on Publisher logs, for ASO transfers there is no central log.

**Comment by sharmaprajesh** [comment]
I will take care of this task. I am starting to understand it.

**Comment by sharmaprajesh** [comment]
@belforte , I have a question from cronjob[1], it has two script :
1. /data/srv/asyncstageout/current/sw.*/*/cms/asyncstageout/*/etc/profile.d/init.sh
2.  /data/srv/asyncstageout/current/apps/asyncstageout/bin/aso_metrics_ora.py 

I understood that aso_metrics_ora.py  is collecting data and pushing to MONIT, but I did not understand purpose of init.sh.
Is there any dependency of aso_metrics_ora.py on init.sh? If not then I will focus on aso_metrics_ora.py only, 
Otherwise- I found  in init.sh[2], having some python package/library paths are setup but did not understand another script dependencies-setup.sh[3] execution within init.sh.

One more thing, Can I redirect output of aso_metrics_ora.py to /tmp/aso_metrics_ora.log i.e. change [1] as:
*/5 * * * * source /data/srv/asyncstageout/current/sw.*/*/cms/asyncstageout/*/etc/profile.d/init.sh ;  python /data/srv/asyncstageout/current/apps/asyncstageout/bin/aso_metrics_ora.py > /tmp/aso_metrics_ora.log 

[1]
*/5 * * * * source /data/srv/asyncstageout/current/sw.*/*/cms/asyncstageout/*/etc/profile.d/init.sh ;  python /data/srv/asyncstageout/current/apps/asyncstageout/bin/aso_metrics_ora.py > /dev/null

[2]
/data/srv/asyncstageout/current/sw.dciangot/slc6_amd64_gcc493/cms/asyncstageout/1.1.0.pre1/etc/profile.d/init.sh

[3]
/data/srv/asyncstageout/v1.1.0.pre1/sw.dciangot/slc6_amd64_gcc493/cms/asyncstageout/1.1.0.pre1/etc/profile.d/dependencies-setup.sh

**Comment by belforte** [comment]
that's simpy the same as what we have for GenrateMONIT.py as
```
 source /data/srv/TaskManager/env.sh &&  export PYTHONPATH="/usr/lib/python2.7/site-packages/:${PYTHONPATH}"
```
setup of the environment is needed for WMCore and CRABServer dependencies. Simply in vocms0105 there was a (very) old (very) different setup,.
Please test on any TW machine in the same way as current crontab
```
# Puppet Name: Send information to elasticsearch MONIT
*/5 * * * * test -f /home/crab3/GenerateMONIT.py && source /data/srv/TaskManager/env.sh &&  export PYTHONPATH="/usr/lib/python2.7/site-packages/:${PYTHONPATH}" && python /home/crab3/GenerateMONIT.py >/dev/null 2>&1
```
as I wrote, I hope that we can unify in a single script (and possibly run on a different VM then the TW, or better yet make it its own  docker container and run anywhere).

**Comment by belforte** [comment]
Please note a defect in current crontab: it picks environment from /data/srv/TaskManager, now that we run TW inside a container that is just an old installation which may rm at any time or simply become obsolete. This should become like Publisher, just one different service to run inside the same TW container. So that you can easily e.g. run it in the K8s cluster to simplify the "only one copy should run at same time" as discussed in the past.

Anyhow, let's make it work first, then you can look into the best deployment strategy.

**Comment by belforte** [comment]
about this
> Can I redirect output of aso_metrics_ora.py to /tmp/aso_metrics_ora.log i.e. change [1] as:
/5 * * * * source /data/srv/asyncstageout/current/sw.//cms/asyncstageout//etc/profile.d/init.sh ; python /data/srv/asyncstageout/current/apps/asyncstageout/bin/aso_metrics_ora.py > /tmp/aso_metrics_ora.log
defintly you can and should, of course. I would simply reuse what we have for GenerateMONIT.py
BUt in the initial phase I think it is better to run it standalone, possibly even interactively in python or pdb shell. Only when you know what it does and that it works, turn it into a crontab.

**Comment by sharmaprajesh** [comment]
I setup above python script in crab-prod-tw02[1] and then execute but got  error[2]:
Understanding the cause of error.

[1]
[root@crab-prod-tw02 ~]# mkdir prajesh
[root@crab-prod-tw02 ~]# cd prajesh/
[root@crab-prod-tw02 prajesh]#
[root@crab-prod-tw02 prajesh]#
[root@crab-prod-tw02 prajesh]# wget https://raw.githubusercontent.com/dmwm/CRABServer/master/src/script/Monitor/aso_metrics_ora.py
--2020-12-03 12:41:33--  https://raw.githubusercontent.com/dmwm/CRABServer/master/src/script/Monitor/aso_metrics_ora.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5727 (5.6K) [text/plain]
Saving to: ‘aso_metrics_ora.py’

100%[===============================================================================================================================================>] 5,727       --.-K/s   in 0s

2020-12-03 12:41:33 (34.8 MB/s) - ‘aso_metrics_ora.py’ saved [5727/5727]

[root@crab-prod-tw02 prajesh]# ll
total 8
-rw-r--r--. 1 root root 5727 Dec  3 12:41 aso_metrics_ora.py
[root@crab-prod-tw02 prajesh]#  source /data/srv/TaskManager/env.sh
[root@crab-prod-tw02 prajesh]#  export PYTHONPATH="/usr/lib/python2.7/site-packages/:${PYTHONPATH}"

[2]
[root@crab-prod-tw02 prajesh]# python aso_metrics_ora.py
No handlers could be found for logger "root"
Traceback (most recent call last):
  File "aso_metrics_ora.py", line 42, in <module>
    data=encodeRequest({'subresource': 'groupedTransferStatistics', 'grouping': 0}))
  File "/data/srv/TaskManager/3.3.2005.rc5/slc7_amd64_gcc630/cms/crabtaskworker/3.3.2005.rc5/lib/python2.7/site-packages/RESTInteractions.py", line 79, in get
    return self.makeRequest(uri = uri, data = data, verb = 'GET')
  File "/data/srv/TaskManager/3.3.2005.rc5/slc7_amd64_gcc630/cms/crabtaskworker/3.3.2005.rc5/lib/python2.7/site-packages/RESTInteractions.py", line 129, in makeRequest
    verbose=self['verbose'])
  File "/data/srv/TaskManager/3.3.2005.rc5/slc7_amd64_gcc630/cms/crabtaskworker/3.3.2005.rc5/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 257, in request
    curl.perform()
pycurl.error: (58, 'could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)')

**Comment by sharmaprajesh** [comment]
withing python script at line 37[1], this code line making server request variable using '/data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy' file which is exists in vocms0105 but not in crab-prod-tw02.[2]

[1]
    server = HTTPRequests('cmsweb.cern.ch',
                          '/data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy',
                          '/data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy')

[2]
[prsharma@vocms0105 ~]$ ll /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy
-r--r-----. 1 crab3 crab3 9239 Dec  1 21:20 /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy

[root@crab-prod-tw02 prajesh]# ll /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy
ls: cannot access /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy: No such file or directory

**Comment by belforte** [comment]
yeah, you need to use the same certificate that TW uses `/data/certs/service*.pem`

**Comment by belforte** [comment]
the two args passed to HTTPRequest are cert and key.

**Comment by sharmaprajesh** [comment]
Thanks Stefano. I update these two. 

Now showing following error:
[root@crab-prod-tw02 prajesh]# python aso_metrics_ora.py
[{"transfers": {"ACQUIRED": {"count": 0, "size": 0}, "FAILED": {"count": 0, "size": 0}, "RETRY": {"count": 0, "size": 0}, "DONE": {"count": 0, "size": 0}, "SUBMITTED": {"count": 0, "size": 0}}, "hostname": "crab-prod-tw02.cern.ch", "type": "aso_total", "publications": {"ACQUIRED": {"count": 0}, "NEW": {"count": 0}, "RETRY": {"count": 0}, "DONE": {"count": 0}, "FAILED": {"count": 0}}, "producer": "crab"}]
Traceback (most recent call last):
  File "aso_metrics_ora.py", line 130, in <module>
    status['transfers'][TRANSFERDB_STATES[doc['transfer_state']]]['count'] = doc['nt']
KeyError: 'NEW'
[root@crab-prod-tw02 prajesh]#

**Comment by belforte** [comment]
maybe this is why it has stopped sending data ?
needs some debugging. Do you feel like doing it ?
Maybe we can give it a shot together to get you started ?

**Comment by sharmaprajesh** [comment]
Problem Found!
===========

results variable at line number 128 having following values:
------------------------------------------------------------------
[
{u'aso_worker': u'asoless', u'nt': 17, u'transfer_state': 0}, 
{u'aso_worker': None, u'nt': 522058, u'transfer_state': 6}, 
{u'aso_worker': u'asoless', u'nt': 1217867, u'transfer_state': 2}, 
{u'aso_worker': u'asoless', u'nt': 466811, u'transfer_state': 5}, 
{u'aso_worker': u'schedd', u'nt': 82407, u'transfer_state': 5}, 
{u'aso_worker': u'schedd', u'nt': 11799835, u'transfer_state': 3}, 
{u'aso_worker': u'asoless', u'nt': 11208, u'transfer_state': 6}, 
{u'aso_worker': u'schedd', u'nt': 48183, u'transfer_state': 0}, 
{u'aso_worker': u'schedd', u'nt': 86742, u'transfer_state': 2}, 
{u'aso_worker': u'asoless', u'nt': 57787155, u'transfer_state': 3}, 
{u'aso_worker': None, u'nt': 5104441, u'transfer_state': 3}, 
{u'aso_worker': u'rucio', u'nt': 1, u'transfer_state': 2}, 
{u'aso_worker': u'rucio', u'nt': 118, u'transfer_state': 3}, 
{u'aso_worker': u'rucio', u'nt': 6, u'transfer_state': 5}, 
{u'aso_worker': None, u'nt': 4439, u'transfer_state': 0}, 
{u'aso_worker': u'schedd', u'nt': 40061, u'transfer_state': 6}]

within the loop i.e. at line 129 following values will be satisfied among the above:
--------------------------------------------------------------------------------------------
{u'aso_worker': u'asoless', u'nt': 17, u'transfer_state': 0}, 
{u'aso_worker': u'asoless', u'nt': 1217867, u'transfer_state': 2}, 
{u'aso_worker': u'asoless', u'nt': 466811, u'transfer_state': 5}, 
{u'aso_worker': u'asoless', u'nt': 11208, u'transfer_state': 6}, 
{u'aso_worker': u'asoless', u'nt': 57787155, u'transfer_state': 3}, 

At line 130, value of doc['transfer_state'] will be:  0,2,5,6,3
So, At line 130, value of TRANSFERDB_STATES[doc['transfer_state']] will be: NEW,FAILED,SUBMITTED,KILL,DONE

BUT
----
status variable at line 126 i.e. tmp variable at line 119 do not have - NEW and KILL with in dict of 'transfers' key,
and even KILLED is not there.

NOTE::TRANSFERDB_STATES = {0: 'NEW', 1: 'ACQUIRED', 2: 'FAILED', 3: 'DONE', 4: 'RETRY', 5: 'SUBMITTED', 6: 'KILL', 7: 'KILLED'}

Solution
=========
We should replace this if condition at line 129:
                    if doc['aso_worker']=="asoless":
with this:
 if doc['aso_worker']=="asoless" and doc['transfer_state'] != 0 and  doc['transfer_state'] != 6 and doc['transfer_state'] != 7:

Updated code is in the crab-prod-tw02 at :  
----------------------------------------------
[root@crab-prod-tw02 prajesh]# pwd
/root/prajesh
[root@crab-prod-tw02 prajesh]# ll
total 12
-rw-r--r--. 1 root root 6085 Dec  4 05:42 aso_metrics_ora.py
-rw-r--r--. 1 root root  421 Dec  4 05:42 tmp_transfer

Now it is working fine
=================
[root@crab-prod-tw02 prajesh]#  python aso_metrics_ora.py
[{"transfers": {"ACQUIRED": {"count": 0, "size": 0}, "FAILED": {"count": 0, "size": 0}, "RETRY": {"count": 0, "size": 0}, "DONE": {"count": 0, "size": 0}, "SUBMITTED": {"count": 0, "size": 0}}, "hostname": "crab-prod-tw02.cern.ch", "type": "aso_total", "publications": {"ACQUIRED": {"count": 0}, "NEW": {"count": 0}, "RETRY": {"count": 0}, "DONE": {"count": 0}, "FAILED": {"count": 0}}, "producer": "crab"}]
[{"transfers": {"ACQUIRED": {"count": 0, "size": 0}, "FAILED": {"count": 1217867, "size": 0}, "RETRY": {"count": 0, "size": 0}, "DONE": {"count": 57787155, "size": 0}, "SUBMITTED": {"count": 466811, "size": 0}}, "hostname": "crab-prod-tw02.cern.ch", "type": "asoless", "publications": {"ACQUIRED": {"count": 0}, "NEW": {"count": 0}, "RETRY": {"count": 0}, "DONE": {"count": 0}, "FAILED": {"count": 0}}, "producer": "crab"}]
[root@crab-prod-tw02 prajesh]#

**Comment by belforte** [comment]
good work Prajesh, thanks.
Now.. workarounds are fine, but we strive to solve problems at the root even if it means to rewrite some code.
Clearly the script author was sloppy here.
You should rather make sure that in lines 50 and 51 the dictionaries are filled with all possible statuses, and best way is to use the list from
```
from ServerUtilities import TRANSFERDB_STATES, PUBLICATIONDB_STATES
```
Maybe the original author did not want to send all the states to MONIT for plotting in Grafana, but in case the way to do is to filter them explicitly with a proper comment before sending to MONIT. Even if I do not know why we should not want to monitor number of files in status NEW.

Indeed, data has appeared  at the other end ... https://monit-grafana.cern.ch/d/JQG5D3mZz/crab-asometrics?viewPanel=2&orgId=11&refresh=30m&from=1606922702880&to=1607095502881&var-HOST=All&var-type=All&var-Destination=All&var-User=All

**Comment by sharmaprajesh** [comment]
Hi @belforte ,

I have created a new script new_aso_metrics_ora.py with the help of old script, which is exists in /root/prajesh directory in crab-prod-tw02.[1]
It is executing without any problem. Output[2]
Please have a look whenever you will have time.
I will put some exception handling after your confirmation.

Thanks and Regards
[1]
```
[root@crab-prod-tw02 prajesh]# ll
total 16
-rw-r--r--. 1 root root 6085 Dec  4 05:42 aso_metrics_ora.py
-rw-r--r--. 1 root root 3780 Dec  5 10:46 new_aso_metrics_ora.py
-rw-r--r--. 1 root root  421 Dec  4 06:07 tmp_transfer
[root@crab-prod-tw02 prajesh]# pwd
/root/prajesh
```
[2]
```
[root@crab-prod-tw02 prajesh]# python new_aso_metrics_ora.py
======================================================================
Row aso_worker     nt        transfer_state
----------------------------------------------------------------------
1   asoless        17        0
2   None           522058    6
3   asoless        1217867   2
4   asoless        466811    5
5   schedd         6793      5
6   schedd         12518274  3
7   asoless        11208     6
8   schedd         43444     0
9   schedd         89200     2
10  asoless        57787155  3
11  None           5104440   3
12  rucio          1         2
13  rucio          118       3
14  rucio          6         5
15  None           4439      0
16  schedd         44911     6
======================================================================
TRANSFERDB_STATES={0: 'NEW', 1: 'ACQUIRED', 2: 'FAILED', 3: 'DONE', 4: 'RETRY', 5: 'SUBMITTED', 6: 'KILL', 7: 'KILLED'}
======================================================================
Row aso_worker     nt        publication_state
----------------------------------------------------------------------
1   asoless        99        0
2   asoless        86        1
3   asoless        488640    2
4   rucio          117       0
5   asoless        47758219  5
6   schedd         9929903   5
7   None           5630466   5
8   schedd         2656813   3
9   schedd         10622     0
10  schedd         18789     2
11  asoless        11236014  3
12  None           113       3
13  rucio          8         5
14  None           356       0
15  schedd         86532     1
======================================================================
PUBLICATIONDB_STATES={0: 'NEW', 1: 'ACQUIRED', 2: 'FAILED', 3: 'DONE', 4: 'RETRY', 5: 'NOT_REQUIRED'}
Filled json doc with   where aso_worker=asoless
----------------------------------------------------------------------
[{"transfers": {"FAILED": {"count": 1217867, "size": 0}, "RETRY": {"count": 0, "size": 0}, "DONE": {"count": 57787155, "size": 0}, "ACQUIRED": {"count": 0, "size": 0}, "NEW": {"count": 17, "size": 0}, "KILL": {"count": 11208, "size": 0}, "SUBMITTED": {"count": 466811, "size": 0}, "KILLED": {"count": 0, "size": 0}}, "hostname": "crab-prod-tw02.cern.ch", "type": "asoless", "publications": {"RETRY": {"count": 0}, "ACQUIRED": {"count": 86}, "FAILED": {"count": 488640}, "DONE": {"count": 11236014}, "NEW": {"count": 99}, "NOT_REQUIRED": {"count": 47758219}}, "producer": "crab"}]
======================================================================
successfully uploaded
```

**Comment by sharmaprajesh** [comment]
```
[root@crab-prod-tw02 prajesh]# cat -n new_aso_metrics_ora.py
     1  #!/usr/bin/env python
     2  """
     3  Kibana monitor script for OracleAso
     4  """
     5  from __future__ import print_function
     6  from __future__ import division
     7
     8  import os
     9  import sys
    10  import json
    11  import time
    12  import pycurl
    13  import urllib
    14  import urllib2
    15  import httplib
    16  import logging
    17  import datetime
    18  import subprocess
    19  import requests
    20  from urlparse import urljoin
    21  from socket import gethostname
    22  from optparse import OptionParser
    23
    24  from RESTInteractions import HTTPRequests
    25  from ServerUtilities import encodeRequest, oracleOutputMapping
    26  from ServerUtilities import TRANSFERDB_STATES, PUBLICATIONDB_STATES
    27
    28  MONIT           ='http://monit-metrics:10012/'
    29  CMSWEB          ='cmsweb.cern.ch'
    30  CERTIFICATE     ='/data/certs/servicecert.pem'
    31  KEY             ='/data/certs/servicekey.pem'
    32  DATA_SOURCE_URL ='/crabserver/prod/filetransfers'
    33
    34  #======================================================================================================================================
    35  def getData(subresource):
    36
    37          server = HTTPRequests(CMSWEB,CERTIFICATE,KEY)
    38          result = server.get(DATA_SOURCE_URL,data=encodeRequest({'subresource': subresource, 'grouping': 0}))
    39
    40          return oracleOutputMapping(result)
    41
    42  #======================================================================================================================================
    43  def printData(data,header):
    44
    45          i=1
    46          print("="*70)
    47          print("%-4s%-15s%-10s%-10s" % header)
    48          print("-"*70)
    49          for row in data:
    50                  print("%-4d%-15s%-10d%-10d" % (i,row[header[1]],row[header[2]],row[header[3]]))
    51                  i=i+1
    52
    53          print("="*70)
    54  #======================================================================================================================================
    55
    56  def fillData(data,dict_key,aso_worker,state,inputDoc):
    57
    58          if state=='transfer_state':
    59                  STATES=TRANSFERDB_STATES
    60          if state=='publication_state':
    61                  STATES=PUBLICATIONDB_STATES
    62
    63          for row in data:
    64                  if row['aso_worker'] == aso_worker:
    65                          inputDoc[dict_key][STATES[row[state]]]['count'] = row['nt']
    66
    67  #======================================================================================================================================
    68  def sendDocument(document):
    69          response = requests.post(MONIT, data=json.dumps(document), headers={ "Content-Type": "application/json; charset=UTF-8"})
    70          return response.status_code
    71  #======================================================================================================================================
    72
    73  inputDoc = {
    74          'producer': 'crab',
    75          'type': 'asoless',
    76          'hostname': gethostname(),
    77          'transfers':{
    78                          'NEW':{'count':0,'size':0},
    79                          'ACQUIRED':{'count':0,'size':0},
    80                          'FAILED':{'count':0,'size':0},
    81                          'DONE':{'count':0,'size':0},
    82                          'RETRY':{'count':0,'size':0},
    83                          'SUBMITTED':{'count':0,'size':0},
    84                          'KILL':{'count':0,'size':0},
    85                          'KILLED':{'count':0,'size':0}
    86          },
    87          'publications':{
    88                          'NEW':{'count':0},
    89                          'ACQUIRED':{'count':0},
    90                          'FAILED':{'count':0},
    91                          'DONE':{'count':0},
    92                          'RETRY':{'count':0},
    93                          'NOT_REQUIRED':{'count':0}
    94          }
    95  }
    96  results=getData('groupedTransferStatistics')
    97  printData(results,('Row','aso_worker','nt','transfer_state'))
    98  print("TRANSFERDB_STATES={0: 'NEW', 1: 'ACQUIRED', 2: 'FAILED', 3: 'DONE', 4: 'RETRY', 5: 'SUBMITTED', 6: 'KILL', 7: 'KILLED'}")
    99  fillData(results,'transfers','asoless','transfer_state',inputDoc)
   100
   101  results=getData('groupedPublishStatistics')
   102  printData(results,('Row','aso_worker','nt','publication_state'))
   103  print("PUBLICATIONDB_STATES={0: 'NEW', 1: 'ACQUIRED', 2: 'FAILED', 3: 'DONE', 4: 'RETRY', 5: 'NOT_REQUIRED'}")
   104  fillData(results,'publications','asoless','publication_state',inputDoc)
   105
   106
   107  print("Filled json doc with   where aso_worker=asoless")
   108  print("-"*70)
   109  print (json.dumps([inputDoc]))
   110
   111  print("="*70)
   112  if sendDocument([inputDoc])==200:
   113          print('successfully uploaded')
   114  else:
   115          print('errors in  uploaded')
```

**Comment by belforte** [comment]
The new code reads well Prajesh. I suggest that you verify that sends same data as old one and then make a PR to replace it.
I have a few comments about style which we can address there.
Then we need to run it and focus on understanding what is being reported and how to improve, the few data points which have been send appeared a constant number of submitted transfers at ~40K...  In the end we need to plot the change of the number of files in any given status over a certain time interval.

**Comment by sharmaprajesh** [comment]
I corrected this plot[1], which was having host value vocms0105 in the query. Now it is showing plots according to values i.e. as previous. @belforte Please correct me if I am wrong.

[1]
https://monit-grafana.cern.ch/d/JQG5D3mZz/crab-asometrics?viewPanel=1&orgId=11&refresh=30m&from=now-90d&to=now

**Comment by sharmaprajesh** [comment]
I also enable MAX count metric in the above plot for my understanding. I will disable it after understanding. I did not create this, it was already there but disabled.

**Comment by belforte** [comment]
thanks for fixing the query.
I confess that I still do not understand these plots.
if it shows number of transfers if DONE status total in the DB (across all partitions) it is totally useless
The derivative should help, but it is constantly zero.
The plot of transfer submitted in the panel above that is also very strange since it is a flatline for prod-tw02 while at least it had some "movement" for 105.
So I can't say if new data feed has a problem or what, but it looks like aside this jump
https://monit-grafana.cern.ch/d/JQG5D3mZz/crab-asometrics?viewPanel=2&orgId=11&from=1608071208540&to=1608153131802&var-HOST=All&var-type=All&var-Destination=All&var-User=All
(partition dropping?)
the total number of submitted transfers is a constant. Which makes no sense.
Also transfers should be DONE or FAILED, can't staty in SUBMITTED forever....

That is something that we never understood, even the old plot fro vocms015 never went to 0, and I never liked it. Now sort of went from bad to worse.

Anyhow we should separate understanding data from reporting to MONIT.
You may want to do a few SQL Count to verify that the number from the script is something that we understand as the result of a query and check that this number is plotted correctly.
At that point we know that we can trust grafana and focus on why that query is not reporting useful information and what to do instead.
But first thing is to know what exactly we are looking at, since honestly I do not know.

**Comment by sharmaprajesh** [comment]
You are right   it shows number of transfers if DONE,SUBMITTED status total in the DB (across all partitions)

TRANSFERS: DONE (derivative 10m)
=============================
https://monit-grafana.cern.ch/d/JQG5D3mZz/crab-asometrics?viewPanel=1&orgId=11&refresh=30m&from=now-1h&to=now&var-HOST=All&var-type=All&var-Destination=All&var-User=All

SQL> select count(*) from FILETRANSFERSDB where TM_ASO_WORKER='asoless' and TM_TRANSFER_STATE=3;

  COUNT(*)
----------
  47954061

TRANSFERS: SUBMITTED (cumulative 10m)
=============================
https://monit-grafana.cern.ch/d/JQG5D3mZz/crab-asometrics?viewPanel=2&orgId=11&refresh=30m&from=now-1h&to=now&var-HOST=All&var-type=All&var-Destination=All&var-User=All

SQL> select count(*) from FILETRANSFERSDB where TM_ASO_WORKER='asoless' and TM_TRANSFER_STATE=5;

  COUNT(*)
----------
    452979

**Comment by sharmaprajesh** [comment]
![image](https://user-images.githubusercontent.com/14272851/102412934-7906f000-3ff4-11eb-843b-256d67b4e4d6.png)

Same value is collected by MONIT script. Look at row 4 and 10

**Comment by belforte** [comment]
by the way, I think that currently we only have TM_ASO_WORKER='schedd'

and I never remember the mapping of those stupid transfer_state numbers into human strings. I wish we had the time to change the bloody code and use names. And may them roast in hell those who put numbers in there to begin with, like if Oracle would not be smart enough to hash strings and use integers anyhow for speed.

So I encourage you to get creative and find out what exactly happens and what we should do instead and if we need to change the queries made by the script, so be it.

**Comment by sharmaprajesh** [comment]
Please look at these lines:

        server = HTTPRequests(CMSWEB,CERTIFICATE,KEY)
        result = server.get(DATA_SOURCE_URL,data=encodeRequest({'subresource': subresource, 'grouping': 0}))

Where:
CMSWEB          ='cmsweb.cern.ch'
DATA_SOURCE_URL ='/crabserver/prod/filetransfers'

AND subresource can be:
groupedTransferStatistics OR 'groupedPublishStatistics 

Do you know where "/crabserver/prod/filetransfers" URL target in "cmsweb.cern.ch", i.e. where these SQL statement/API defined So that I can change them according  to our requirements.

**Comment by belforte** [comment]
please start by making the plots for the correct asoworker value.

Changing SQL queries inside Crabserver is always a pain, if nothing else because updating of cmsweb needs to go through Imran and monthly cycle, plus the need of making sure which other part of the code may be using those which is not easy at all. So we will look at what's available already first.  Going from and URL to the SQL is the most intricated part of CRAB code, and I often get lost in it... which is another reason for avoiding changing as  much as possible.

**Comment by sharmaprajesh** [comment]
I replace 'asoless' with 'schedd' in MONIT script.

**Comment by belforte** [comment]
thanks Prajesh, things look much more sane now
![Screenshot from 2020-12-17 10-25-24](https://user-images.githubusercontent.com/1837785/102468818-a1541600-4017-11eb-85c3-bbe35102b4ae.png)

by the way, if the script already selects the asoworker, there's no point to select it again in the query. I think it is better to remove the selection in the script and keep the filtering in grafana. The old stuff for "asoless" will go away in time as we drop old partitions.

**Comment by belforte** [comment]
The transfer FAILED plot still is wrong, the derivative should be similar to that for DONE, i.e. the total number should be (hopefully slowly) increase with time and this plot will indicate how many transfer failed per 10min (we'll see later about possibly changing time bin).

**Comment by belforte** [comment]
I think it is high time that you update the script source in this repository.  It does not need to be perfect, we can always change, but I do not like that we run something different from what's in the repository.

**Comment by belforte** [comment]
OK. Failed plot only needed to have MAX removed.
The plot names could be improved (what does cumulative mean ?), the TRANSFER plot may be better show average per bin, rather than max. We can discuss bars vs. lines... could make a plot of failed/done percentage etc. but things look basically correct to me. You can look into adding same plots for publications ! Done and Failed as derivative (change in a given time interval), New and Aquired as value (how many are in each status at any given time).

**Comment by belforte** [comment]
Anyhow, I do not think we need to use a GH to discuss changes to the dashboard. This issue can be closed as soon as we have a working script stably running in a controlled way, integrated with GenerateMONIT.

**Comment by sharmaprajesh** [comment]
![image](https://user-images.githubusercontent.com/14272851/102472145-4b529300-4056-11eb-87ba-49e170f8a4fa.png)
type:asoless in the above query is related to only an attribute in the following dictionary, and there is no relation of this attribute  to the selection of values in inputDoc dictionary.
![image](https://user-images.githubusercontent.com/14272851/102472084-3aa21d00-4056-11eb-9eda-19836b196da3.png)

According to my understanding, we have two option:
1. We can remove type:asoless from grafana query  as well as from inputDoc dictionary.
2. We can remove remove type:asoless from grafana query and replace it with type:schedd in inputDoc dictionary.

**Comment by belforte** [comment]
I see.
I think some type string is required by MONIT, please check with Ceyhun and/or CERN Monit team.
And the fact that this string is set to 'asoless' is simpy incidental and confusing .
You can check with experts if it is possible to change it to avoid being confused, or are stuck with it. and then need to add asoworker to the data so that we can filter on it in grafana. I mean a data filed called asoworker, not a metadata filed called type, which is what it has now.
hostname is also totally irrelevant, this script sends information obtained from the DB, it does not matter where it runs, it is a relic from old ASO implementation using multiple CoucDB instances (a mess) which we removed years ago. Again, if you need to send it, do it, but it is pointless to filter on it. Rather one could think of replicatin queries on preprod DB and making it a variable to filter one (well.. same from TW metrics in main CRAB Metric dashboard, actually).

**Comment by belforte** [comment]
Since script works now, I think it is better to close this and move to an ad-hoc one the remaining pending request to add asoworker to what is sent to MONIT.
