### ISSUE TITLE
RUCIO_Transfer.py: Things need to be done before run test in larger scale.

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7632]
The goal of this issue is to track todo lists that need to be done before we can run automated tests at large scale.

Things need to be done are (mostly copy from https://github.com/dmwm/CRABServer/issues/7524#issuecomment-1543590542): 

- [x] Fix `add_replicas` to try again instead of fail them (It should not failed on this step).
- [x] Update correct status to database when files transfer is completed.
- [x] bookkeeping locks monitoring.
  - Need to review it again because it is affected by separating publish and transfer container.
- [x] 1 container for multiple tasks (separate publish and transfer container)
  - However, there is no guarantee it will survive race condition, especially when close the dataset and open new one.
- [x] Fix rucio config broken on `T2_DE_DESY`, and more. https://github.com/dmwm/CRABServer/issues/7740
- [x] Make it run on dev environment.

**Comment by belforte** [comment]
I have not tried to really understand the problem with DESY, but I find it hard to image that a well run site like T2_DE_DESY has a bad configuration, maybe this is us who did not understand how to use the information (so we can fix silently) or, worse, some insufficient specification on how sites should be configured. If the latter it can happen on more sites and we need to get Rucio and SiteFacilities involved.

**Comment by novicecpp** [comment]
About that the site config is not actual problem but it is CMSRucio itself that have weird configuration with temp area.
I have consulted with Rahul and he suggest to open issue with CMSRucio repo and discuss there.

**Comment by belforte** [comment]
yeah, it is a thin and blurred line how much temp_RSE config is a site responsibility vs. a CMS-Rucio vs. a CMS_SiteFacilities responsibility. DIfferent people likely have different ideas where that line lies and all those things change with time, of course

**Comment by novicecpp** [comment]
All list above is now solved (note for broken sites on `T2_DE_DESY` and `T2_UK_SGrid_Bristol` is fixed by hardcode in the scripts.)

3 things that still needs to figure it out before closing this issues.

- [ ] Close the dataset when (in OR)
  - It has 100 files
  - 6 hours have passed since last time a block was added to DBS for this task
  - The task has terminated (this was done as a courtesy to user, in case you have a task with 10 jobs, which completed in 1h and do not want to wait 6h to have crab status to say “publication completed”)

If we close it when the above conditions meet, the next iteration will create a new dataset immediately, and it will close in the next 6 hours. So we have many closed datasets without any replicas inside a container. In theory, it may be alright because we use block names in db to publish to DBS, which always has one or more files in it. 

- [ ] When `crabConfig.Data.publication=False`, `publishname` is always same (`FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER`). 

It need to be unique value for each task. Workaround for this is to disable register replica in publish container, but it will defeat the reason of have files manage in Rucio.

- [ ] What should we do if replicas stuck form n hours?

**Comment by belforte** [comment]
>   If we close it when the above conditions meet, the next iteration will create a new dataset immediately, and it will close in the next 6 hours.

why do we create a new dataset if we have no files to put in it ? Seems something easy to avoid.

I am not sure I fully understand 2nd point. Let's talk about it. In case it should not be too difficult to create a FakeDataset which is unique for each task

**Comment by novicecpp** [comment]
> why do we create a new dataset if we have no files to put in it ? Seems something easy to avoid.

I agree. It should easy to fix but maybe require a lot of code change, same as fake publication.
I will have a look.

**Comment by belforte** [comment]
1. look at transfers.txt
2. no new file ? exit (even as simple as count lines and compare with stored last-line value)
3. use current code

fake publication, I do not know off-hand.

**Comment by novicecpp** [comment]
Closing dataset when time has passed is easier to fix than I though. Now it fixed in my private branch.

For FakeDataset I added fix in [PostJob.py#L1627-L1630](https://github.com/novicecpp/CRABServer/blob/47e8804964bc23b760cae497e4e33d3cd24a0942/src/python/TaskWorker/Actions/PostJob.py#L1627-L1630) file. I am not sure if this is proper solution or just workaround. Also, I wonder why we update `tasks.tm_output_dataset` in postjob instead of in REST/TW.

**Comment by belforte** [comment]
> I am not sure if this is proper solution or just workaround. 

IIUC we still have a FakeDataset here, simply a different one for each task. Which is what we require in order to have a different container for each task. So I'd call it a fix .

**Comment by novicecpp** [comment]
- [ ] https://github.com/dmwm/CRABServer/issues/7741

**Comment by novicecpp** [comment]
All done.
